### ISSUE TITLE
请删除关于“just.monika.*"的内容

### ISSUE THREAD

**Issue by ypo-GitHub** [cubk/how-to-code-shitclient#3]
请删除关于“just.monika.*"的内容

**Comment by cubk** [comment]
典型example，删什么

**Comment by ypo-GitHub** [comment]
delete it or your mom dead

**Comment by ImCzf233** [comment]
删牛魔酬宾

**Comment by ImCzf233** [comment]
主播你有反编译我代码的时间还不如自己写一个端子
开裂我端子的反编译我几行代码死几个妈
反编译我代码油饼食不食
主播你有反编译我代码的时间还不如自己写一个端子.主播你IQ行不行啊

**Comment by ypo-GitHub** [comment]
> 主播你有反编译我代码的时间还不如自己写一个端子 开裂我端子的反编译我几行代码死几个妈 反编译我代码油饼食不食 主播你有反编译我代码的时间还不如自己写一个端子.主播你IQ行不行啊

NQJSL

**Comment by ypo-GitHub** [comment]
delete it or your mom dead

**Comment by ypo-GitHub** [comment]
delete it or your mom dead

**Comment by ll11l1lIllIl1lll** [comment]
stays mad
